// Generates Paradox-script and localisation text for a civic mod project.

import type { AiWeight, Civic, ModProject } from "../types";
import { serializeNodes } from "./conditions";

/** Sanitize a free-form name into a valid lowercase script key. */
export function toKey(prefix: string, name: string): string {
  const slug = name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "");
  return `${prefix}${slug || "unnamed"}`;
}

/** Normalize a free-form prefix into a lowercase id-safe namespace (no trailing _). */
export function normalizePrefix(prefix: string): string {
  return prefix
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "");
}

/**
 * The effective, exported script key for a civic: the base key with the mod
 * prefix prepended, unless the project has no prefix or the civic opts out.
 */
export function effectiveCivicKey(project: ModProject, civic: Civic): string {
  const prefix = normalizePrefix(project.idPrefix);
  if (!prefix || civic.noPrefix) return civic.key;
  return `${prefix}_${civic.key}`;
}

/** Format a number for Paradox script without floating-point noise. */
function num(n: number): string {
  if (!Number.isFinite(n)) return "0";
  // Up to 4 decimals, trailing zeros trimmed.
  return parseFloat(n.toFixed(4)).toString();
}

/** Escape a string for use inside a quoted yml localisation value. */
function locEscape(s: string): string {
  return s.replace(/"/g, '\\"');
}

/** The description localisation key for a given (effective) civic key. */
export function descKey(civicKey: string): string {
  return `${civicKey}_desc`;
}

/** Render a named condition block (`potential`/`possible`), or "" if empty. */
function renderCondBlock(name: string, nodes: Civic["possible"]): string {
  if (!nodes || nodes.length === 0) return "";
  return `\t${name} = {\n${serializeNodes(nodes, 2)}\n\t}\n`;
}

// AI weight factors defer to the game's standard scripted variables.
const AI_FACTORS = {
  match: "@ai_civic_personality_match_factor",
  mismatch: "@ai_civic_personality_mismatch_factor",
  forbid: "@ai_civic_personality_forbid_factor",
} as const;

/** Render the `ai_weight = { ... }` block, or "" if no personalities are bucketed. */
function renderAiWeight(ai: AiWeight): string {
  const groups: string[] = [];
  for (const bucket of ["match", "mismatch", "forbid"] as const) {
    const personalities = ai[bucket];
    if (personalities.length === 0) continue;
    const checks = personalities
      .map((p) => `\t\t\t\thas_ai_personality = ${p}`)
      .join("\n");
    groups.push(
      `\t\tmodifier = {\n\t\t\tfactor = ${AI_FACTORS[bucket]}\n\t\t\tOR = {\n${checks}\n\t\t\t}\n\t\t}`,
    );
  }
  if (groups.length === 0) return "";
  return `\tai_weight = {\n\t\tbase = @ai_civic_default_base_weight\n${groups.join(
    "\n",
  )}\n\t}\n`;
}

/** Generate the full civics .txt file content for the project. */
export function generateCivicsFile(project: ModProject): string {
  const blocks = project.civics.map((civic) => {
    const key = effectiveCivicKey(project, civic);
    const potential = renderCondBlock("potential", civic.potential);
    const possible = renderCondBlock("possible", civic.possible);
    const modifierLines = civic.modifiers
      .map((m) => `\t\t${m.key} = ${num(m.value)}`)
      .join("\n");
    const modifierBlock =
      civic.modifiers.length > 0 ? `\tmodifier = {\n${modifierLines}\n\t}\n` : "";
    const aiWeight = renderAiWeight(civic.aiWeight);

    return (
      `${key} = {\n` +
      `\tdescription = "${descKey(key)}"\n` +
      potential +
      possible +
      modifierBlock +
      `\trandom_weight = { base = @civic_default_random_weight }\n` +
      aiWeight +
      `}\n`
    );
  });

  return (
    `# Generated by Stellaris Modding Utilities\n` +
    `# Mod: ${project.modName}\n\n` +
    blocks.join("\n")
  );
}

/** Generate the english localisation .yml content (without the leading BOM). */
export function generateLocalisation(project: ModProject): string {
  const lines = ["l_english:"];
  for (const civic of project.civics) {
    const key = effectiveCivicKey(project, civic);
    lines.push(` ${key}:0 "${locEscape(civic.name)}"`);
    lines.push(` ${descKey(key)}:0 "${locEscape(civic.description)}"`);
  }
  return lines.join("\n") + "\n";
}

/** Generate descriptor.mod content. */
export function generateDescriptor(project: ModProject): string {
  return (
    `name="${project.modName}"\n` +
    `version="${project.version}"\n` +
    `supported_version="${project.supportedVersion}"\n` +
    `tags={\n\t"Gameplay"\n}\n`
  );
}
