// Generates Paradox-script and localisation text for a civic mod project.

import type { Civic, ModProject } from "../types";

/** Sanitize a free-form name into a valid lowercase script key. */
export function toKey(prefix: string, name: string): string {
  const slug = name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "");
  return `${prefix}${slug || "unnamed"}`;
}

/** Format a number for Paradox script without floating-point noise. */
function num(n: number): string {
  if (!Number.isFinite(n)) return "0";
  // Up to 4 decimals, trailing zeros trimmed.
  return parseFloat(n.toFixed(4)).toString();
}

/** Escape a string for use inside a quoted yml localisation value. */
function locEscape(s: string): string {
  return s.replace(/"/g, '\\"');
}

/** The civic's description localisation key. */
export function descKey(civic: Civic): string {
  return `${civic.key}_desc`;
}

/** Render the `possible = { ... }` requirement block, or "" if unrestricted. */
function renderRequirements(civic: Civic): string {
  const { ethics, authorities } = civic.requirements;
  const lines: string[] = [];

  if (ethics.length > 0) {
    const inner = ethics.map((e) => `\t\t\tvalue = ${e}`).join("\n");
    lines.push(`\t\tethics = {\n${inner}\n\t\t}`);
  }
  if (authorities.length === 1) {
    lines.push(`\t\tauthority = {\n\t\t\tvalue = ${authorities[0]}\n\t\t}`);
  } else if (authorities.length > 1) {
    const inner = authorities.map((a) => `\t\t\t\tvalue = ${a}`).join("\n");
    lines.push(`\t\tauthority = {\n\t\t\tOR = {\n${inner}\n\t\t\t}\n\t\t}`);
  }

  if (lines.length === 0) return "";
  return `\tpossible = {\n${lines.join("\n")}\n\t}\n`;
}

/** Generate the full civics .txt file content for the project. */
export function generateCivicsFile(project: ModProject): string {
  const blocks = project.civics.map((civic) => {
    const possible = renderRequirements(civic);
    const modifierLines = civic.modifiers
      .map((m) => `\t\t${m.key} = ${num(m.value)}`)
      .join("\n");
    const modifierBlock =
      civic.modifiers.length > 0 ? `\tmodifier = {\n${modifierLines}\n\t}\n` : "";

    return (
      `${civic.key} = {\n` +
      `\tdescription = "${descKey(civic)}"\n` +
      possible +
      modifierBlock +
      `\trandom_weight = { base = 1 }\n` +
      `}\n`
    );
  });

  return (
    `# Generated by Stellaris Civic Forge\n` +
    `# Mod: ${project.modName}\n\n` +
    blocks.join("\n")
  );
}

/** Generate the english localisation .yml content (without the leading BOM). */
export function generateLocalisation(project: ModProject): string {
  const lines = ["l_english:"];
  for (const civic of project.civics) {
    lines.push(` ${civic.key}:0 "${locEscape(civic.name)}"`);
    lines.push(` ${descKey(civic)}:0 "${locEscape(civic.description)}"`);
  }
  return lines.join("\n") + "\n";
}

/** Generate descriptor.mod content. */
export function generateDescriptor(project: ModProject): string {
  return (
    `name="${project.modName}"\n` +
    `version="${project.version}"\n` +
    `supported_version="${project.supportedVersion}"\n` +
    `tags={\n\t"Gameplay"\n}\n`
  );
}
